
import java.io.File;
import java.io.FileNotFoundException;

/* Chris Cruzen
 * Compilers
 * 04.04.2020
 *
 * TestScanner is the root class of Project1. This class takes user input
 * either as a filename to read or as a command line input stream. It then
 * passes that input to the Scanner class and iterates through each token
 * generated by the scanner.
 */


public class TestScanner {


    /*----- Global Constants -----*/

    private final static String INPUT_FILE_EXTENSION = ".sp2020";
    private final static String ERROR_EXTRA_ARGUMENTS = "Too many arguments. Aborting.";
    private final static String ERROR_EMPTY_INPUT = "Empty input provided. Aborting.";
    private final static String ERROR_READING_FILE = "Error reading file. Aborting.";


    /*----- Main Method -----*/

    public static void main(String[] args) {


        /*--- Variable Declarations ---*/

        String inputFileName = null;
        String input = "";


        /*--- Parse Input ---*/

        if (args.length > 1) {
            System.out.println(ERROR_EXTRA_ARGUMENTS);
            System.exit(0);
        } else if (args.length == 1) {

            // Verify Filename Format
            inputFileName = args[0];
            if (!inputFileName.contains(INPUT_FILE_EXTENSION)) {
                inputFileName = inputFileName + INPUT_FILE_EXTENSION;
            }

            // Read File
            input = readFile(inputFileName);
        } else {
            input = readInputStream();
        }


        /*--- Validate Input ---*/

        if (input.length() == 0) {
            System.out.println(ERROR_EMPTY_INPUT);
            System.exit(0);

        }


        /*--- Create Scanner ---*/

        Scanner scanner = new Scanner(input);


        /*--- Print Tokens ---*/

        Token token = scanner.getNextToken();
        while (!token.toString().equals("{}")) {
            System.out.println(token);
            token = scanner.getNextToken();
        }

    }


    /*----- Utility Methods -----*/

    private static String readFile(String filename) {

        try {

            // Read From File
            File inputFile = new File(filename);
            java.util.Scanner scanner = new java.util.Scanner(inputFile);
            StringBuilder builder = new StringBuilder();
            while (scanner.hasNext()) {
                builder.append(" ");
                builder.append(scanner.next());
            }
            scanner.close();

            // Return Contents
            return builder.toString().trim();

        } catch (FileNotFoundException e) {
            System.out.println(ERROR_READING_FILE);
            System.exit(0);
            return "";
        }
    }

    private static String readInputStream() {

        // Read Input Stream
        java.util.Scanner scanner = new java.util.Scanner(System.in);
        StringBuilder builder = new StringBuilder();
        while (scanner.hasNext()) {
            builder.append(" ");
            builder.append(scanner.next());
        }
        scanner.close();

        // Return Input
        return builder.toString().trim();
    }
}
